// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

// Signup
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

// GET COLLECTIONS
export const GET_COLLECTION_REQUEST = 'GET_COLLECTION_REQUEST'
export const GET_COLLECTION_SUCCESS = 'GET_COLLECTION_SUCCESS'
export const GET_COLLECTION_FAILURE = 'GET_COLLECTION_FAILURE'

// PUT COLLECTION ITEMS
export const PUT_COLLECTION_REQUEST = 'PUT_COLLECTION_REQUEST'
export const PUT_COLLECTION_SUCCESS = 'PUT_COLLECTION_SUCCESS'
export const PUT_COLLECTION_FAILURE = 'PUT_COLLECTION_FAILURE'

// DELETE COLLECTION ITEMS
export const DELETEITEM_COLLECTION_REQUEST = 'DELETEITEM_COLLECTION_REQUEST'
export const DELETEITEM_COLLECTION_SUCCESS = 'DELETEITEM_COLLECTION_SUCCESS'
export const DELETEITEM_COLLECTION_FAILURE = 'DELETEITEM_COLLECTION_FAILURE'

// DELETE ENTIRE COLLECTION
export const DELETEWHOLE_COLLECTION_REQUEST = 'DELETEWHOLE_COLLECTION_REQUEST'
export const DELETEWHOLE_COLLECTION_SUCCESS = 'DELETEWHOLE_COLLECTION_SUCCESS'
export const DELETEWHOLE_COLLECTION_FAILURE = 'DELETEWHOLE_COLLECTION_FAILURE'

// GET ENTITIES
export const GET_ENTITY_REQUEST = 'GET_ENTITY_REQUEST'
export const GET_ENTITY_SUCCESS = 'GET_ENTITY_SUCCESS'
export const GET_ENTITY_FAILURE = 'GET_ENTITY_FAILURE'

// PUT ENTITIES
export const PUT_ENTITY_REQUEST = 'PUT_ENTITY_REQUEST'
export const PUT_ENTITY_SUCCESS = 'PUT_ENTITY_SUCCESS'
export const PUT_ENTITY_FAILURE = 'PUT_ENTITY_FAILURE'

// DELETE ENTITIES
export const DELETE_ENTITY_REQUEST = 'DELETE_ENTITY_REQUEST'
export const DELETE_ENTITY_SUCCESS = 'DELETE_ENTITY_SUCCESS'
export const DELETE_ENTITY_FAILURE = 'DELETE_ENTITY_FAILURE'